const sampleListings = [
  {
    title: "Boys PG near College",
    description: "Affordable PG with food and WiFi",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2" },
    price: 4000,
    location: "Indore",
    country: "India",
    college: "DAVV College",
    type: "shared",
    amenities: ["wifi", "food"],
    distance: 2,
  },
  {
    title: "Girls Hostel Secure",
    description: "Safe hostel with CCTV and security",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1554995207-c18c203602cb" },
    price: 6500,
    location: "Indore",
    country: "India",
    college: "IIT Indore",
    type: "single",
    amenities: ["wifi", "security"],
    distance: 3,
  },
  {
    title: "all room",
    description: "Cheap room for students",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267" },
    price: 2500,
    location: "Bhopal",
    country: "India",
    college: "MANIT Bhopal",
    type: "shared",
    amenities: ["wifi"],
    distance: 1,
  },
  {
    title: "Luxury PG",
    description: "Premium PG with all facilities",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c" },
    price: 10000,
    location: "Indore",
    country: "India",
    college: "DAVV College",
    type: "single",
    amenities: ["wifi", "food", "laundry"],
    distance: 2,
  },
  {
    title: "Student Flat 2BHK",
    description: "Perfect for 2-3 students sharing",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae" },
    price: 12000,
    location: "Bhopal",
    country: "India",
    college: "LNCT Bhopal",
    type: "flat",
    amenities: ["wifi", "parking"],
    distance: 4,
  },
  {
    title: "Girls PG Affordable",
    description: "Affordable PG for girls",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511" },
    price: 5000,
    location: "Indore",
    country: "India",
    college: "DAVV College",
    type: "shared",
    amenities: ["wifi", "food"],
    distance: 2,
  },
  {
    title: "Near College Hostel",
    description: "Walking distance from college",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb" },
    price: 7000,
    location: "Bhopal",
    country: "India",
    college: "MANIT Bhopal",
    type: "single",
    amenities: ["wifi", "security"],
    distance: 1,
  },
  {
    title: "Cheap Shared Room",
    description: "Very budget friendly option",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1484154218962-a197022b5858" },
    price: 2000,
    location: "Indore",
    country: "India",
    college: "IIT Indore",
    type: "shared",
    amenities: [],
    distance: 3,
  },
  {
    title: "Modern Student Flat",
    description: "Fully furnished modern flat",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1494526585095-c41746248156" },
    price: 15000,
    location: "Indore",
    country: "India",
    college: "DAVV College",
    type: "flat",
    amenities: ["wifi", "parking", "laundry"],
    distance: 5,
  },
  {
    title: "Hostel with Food",
    description: "Includes breakfast and dinner",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1560185007-5f0bb1866cab" },
    price: 5500,
    location: "Bhopal",
    country: "India",
    college: "LNCT Bhopal",
    type: "shared",
    amenities: ["wifi", "food"],
    distance: 2,
  }
];

module.exports = sampleListings;